server:
  port: 7070
  tomcat:
    threads:
      max: 200 # Maximum concurrent request threads
      min-spare: 10 # Minimum idle threads to be kept available

cache:
  size: 3

order:
  leader:
    url: http://localhost:9091
  replicas:
    - http://localhost:9091
    - http://localhost:9092
    - http://localhost:9093

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: frontend-service
