server:
  port: 9093
  tomcat:
    threads:
      max: 200
      min-spare: 10

replica:
  id: 3
  all:
    - http://localhost:9091
    - http://localhost:9092
    - http://localhost:9093
#  followers: []

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: order-service
